version: '2'

services:
  glacier:
    image: ${REGISTRY_URL}/glacier-cli
    volumes: 
    - $GLACIER_DATA:/usr/share/glacier/data
    environment: 
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_DEFAULT_REGION
    - AWS_VAULT
    - ES_HOST
    - ES_PORT
    - ES_USER
    - ES_PASSWORD
    - ES_INDEX
    - ES_TYPE
    - ES_USE_SSL
    - PART_SIZE